export enum EventTag {
    ENTER_GAME = "ENTER_GAME",
    LOGIN_FINISH = "LOGIN_FINISH",
    LEVEL_START = "LEVEL_START",
    CLICK_AD = "CLICK_AD",
    LEVEL_FAIL = "LEVEL_FAIL",
    LEVEL_PASS = "LEVEL_PASS",
    AD_REVIVE = "AD_REVIVE",
    AD_REFERSH = "AD_REFERSH",
    AD_SORT = "AD_SORT",
    AD_VIP = "AD_VIP",
    CLICK_VIRTUAL_BANNER = "CLICK_VIRTUAL_BANNER",
}