const fs=require('node:fs'),assert=require('node:assert/strict');
const scene=JSON.parse(fs.readFileSync('assets/gamescene/RhythmCatFeedGameScene.scene'));const c=scene.find(v=>v.catFrames&&v.foodPool);
const editorIds=scene.filter(v=>v._id).map(v=>v._id);assert.equal(new Set(editorIds).size,editorIds.length,'appended button must retain unique editor IDs');
assert(c);assert.equal(c.cats.length,2);assert.equal(c.hearts.length,3);assert.equal(c.foodFrames.length,7);assert.equal(c.foodPool.length,96);
assert.equal(c.catchRadius,52);assert.equal(c.blackCatCatchBonus,6);assert.equal(c.lateCatchGrace,.1);assert.equal(c.dragSensitivity,1.1);
function refs(value){if(!value||typeof value!=='object')return;if('__id__'in value)assert(scene[value.__id__],`invalid ${value.__id__}`);for(const x of Object.values(value))refs(x)}refs(scene);
for(const key of ['layoutRoot','background','touchSurface','scoreLabel','hintLabel','track','backButton','resultOverlay','resultTitle','resultScore','replayButton','homeButton','slowdownButton','slowdownTitle','slowdownDetail'])assert(scene[c[key].__id__],key);
const slowButton=scene[c.slowdownButton.__id__],slowNode=scene[slowButton.node.__id__],root=scene[c.layoutRoot.__id__];
assert(slowNode._active);assert(slowButton._interactable);assert.equal(slowNode._parent.__id__,c.layoutRoot.__id__);
assert(root._children.findIndex(r=>r.__id__===slowButton.node.__id__)>root._children.findIndex(r=>r.__id__===c.touchSurface.__id__),'reward button must receive touches above the drag surface');
assert.equal(scene[c.slowdownTitle.__id__]._string,'降速');assert(!scene[scene[c.slowdownDetail.__id__].node.__id__]._active);
const component=(id,type)=>scene[scene[id]._components.find(r=>scene[r.__id__].__type__===type).__id__];
assert.equal(component(slowButton.node.__id__,'cc.Sprite')._spriteFrame.__uuid__,JSON.parse(fs.readFileSync('assets/res/juggleBallGame/slowdown-button.png.meta')).uuid+'@f9941');
assert.equal(component(c.slowdownBadge.__id__,'cc.Sprite')._spriteFrame.__uuid__,JSON.parse(fs.readFileSync('assets/res/texture/UIs/ad_badge_cartoon_red.png.meta')).uuid+'@f9941');
assert.equal(component(slowButton.node.__id__,'cc.UITransform')._contentSize.width,128);
assert.equal(c.slowTrack.__uuid__,JSON.parse(fs.readFileSync('assets/res/rhythmCatFeed/track-slow.mp3.meta')).uuid);
assert.equal(scene[c.track.__id__]._clip.__uuid__,JSON.parse(fs.readFileSync('assets/res/rhythmCatFeed/track-normal.mp3.meta')).uuid);
assert.equal(slowNode._lpos.y,-465,'reward button occupies the empty floor below the cats');
assert.equal(scene[c.resultOverlay.__id__]._active,false);assert(scene.some(v=>v.__type__==='cc.BlockInputEvents'));assert.equal(scene[c.track.__id__]._playOnAwake,false);
const lobby=JSON.parse(fs.readFileSync('assets/gamescene/NewMainScene.scene'));const main=lobby.find(v=>v.rhythmCatButton);assert(main);assert.equal(lobby[lobby[main.rhythmCatButton.__id__].node.__id__]._name,'RhythmCatCard');
const {loadTs}=require('./rhythm_cat_test_helpers.cjs');const chart=loadTs('assets/scripts/rhythmCatChart.ts').RHYTHM_CAT_CHART;assert(new Set(chart.map(n=>n.id)).size===chart.length);assert(chart.every(n=>n.hitTime>=0&&n.hitTime<=32.666667&&n.x>=0&&n.x<=1));for(let t=0;t<32.7;t+=.05)assert(chart.filter(n=>n.hitTime+c.lateCatchGrace>=t&&(n.hitTime-t)*c.fallSpeed<801).length<=c.foodPool.length);
console.log('rhythm cat scene: references, authored UI, pool capacity, soundtrack, chart and main card passed');
